### ISSUE TITLE
Missing Frames.json

### ISSUE THREAD

**Issue by HiveHead** [RealSput/blend-to-gradient#3]
everytime i run the script it cant find frames.json cause it does not exist how do i get this file.

**Comment by ivythegreenest** [comment]
you're supposed to configure and run the Python script inside of the Blender text editor

**Comment by HiveHead** [comment]
ohhhhhhhh

**Comment by HiveHead** [comment]
i ran it but it there was an error:
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
i used the test teapot provided

**Comment by HiveHead** [comment]
i figured out the last one but now i am getting
![image](https://github.com/RealSput/blend-to-gradient/assets/130176946/af7cf1fb-51ac-4b8a-bfd7-7e4d44163423)

**Comment by hex-waffle** [comment]
i figured it out

**Comment by HiveHead** [comment]
i figured it out just rename the object to frame_1.obj
